### ISSUE TITLE
AnimeSuge website taken down

### ISSUE THREAD

**Issue by kookie99** [MALSync/MALSync#2647] opened 2024-10-17 22:25 UTC
### Describe the Bug

So, I was a user of AnimeSuge but recently they took down their website. I just thought I would mention this so it could be edited in the supported sites section. (:

### Steps to reproduce the behavior

.

### Browser

edge

### Type

Extension

### URL

https://animesuge.to/

**Comment by henrik9999** [comment] 2024-10-17 22:26
Duplicate of #2568

**Closed by henrik9999** 2024-10-17 22:26 UTC
