### ISSUE TITLE
MAL import not working it says invalid format 

### ISSUE THREAD

**Issue by RootAndroid58** [MALSync/MALSync#512] opened 2020-11-04 19:04 UTC
**Describe the bug**
Mal import in both chrome extension and mal script is not working 
It says its in invalid format 
[malsync_2020_11_01.txt](https://github.com/MALSync/MALSync/files/5489939/malsync_2020_11_01.txt)
help me to import this !Just formatted the pc and this is the file i exported 
![image](https://user-images.githubusercontent.com/28777412/98156627-12bf8580-1efe-11eb-8351-417b11c4ca9d.png)

OO got the solution i 
https://jsonlint.com/ to validate the json and then the import worked thank god but ....

**Steps to reproduce the behavior:**
open mal and go to settings -> click on export now try to import (if you dont have then can use my export )

**to make the file work :**
add 
`"}}` to the end and it will import XD atleast that jsonlint showed to make a valid json

**Comment by lolamtisch** [comment] 2020-11-09 13:32
I could not reproduce getting an broken export like that.

But I found a problem during import, that it hits the extension rate limit and ignores the rest. That will be fixed with the next release.

**Closed** 2020-12-16 14:58 UTC
Labels: Done for future release, bug
