### ISSUE TITLE
[Website Request] shiroko

### ISSUE THREAD

**Issue by NameTrillion** [MALSync/MALSync#2626] opened 2024-10-02 13:48 UTC
### Website name

shiroko

### Website link

https://shiroko.co/

### Website language(s)

english

### Other details

It's a beautifully laid out website thematically, would be nice to have it added.

**Comment by henrik9999** [comment] 2024-10-02 13:49
duplicate of #2575

**Closed by henrik9999** 2024-10-02 13:49 UTC
Labels: New Website
