### ISSUE TITLE
[Website Request] anikoto.to

### ISSUE THREAD

**Issue by Ishkei** [MALSync/MALSync#2728] opened 2024-12-10 02:36 UTC
### Website name

anikoto

### Website link

https://anikoto.to/home

### Website language(s)

English

### Other details

This site is similar to Aniwave. It lets you import MAL & Anilist.

**Comment by henrik9999** [comment] 2024-12-17 20:37
Duplicate of #2643

**Closed by henrik9999** 2024-12-17 20:37 UTC
Labels: New Website
