### ISSUE TITLE
website list

### ISSUE THREAD

**Issue by Tropical2497** [MALSync/MALSync#2711] opened 2024-11-27 22:32 UTC
### Describe the Bug

The list:https://github.com/MALSync/MALSync/blob/master/pages.md
Seems outdated, for example: aniwave,anix don't exist anymore.
I am not sure if the features shown in the file are accurate either for every site.

### Steps to reproduce the behavior

click on a dead link

### Browser

firefox(doesn't matter)

### Type

Extension

### URL

https://github.com/MALSync/MALSync/blob/master/pages.md

**Comment by henrik9999** [comment] 2024-11-27 22:35
Duplicate of #2568 
The list will get updated on the next release

**Closed by henrik9999** 2024-11-27 22:35 UTC
