### ISSUE TITLE
[Website Request] Hotstar (Disney+ Hotstar)

### ISSUE THREAD

**Issue by JDKamalakar** [MALSync/MALSync#2494] opened 2024-07-01 18:55 UTC
### Website name

Disney+Hotstar

### Website link

https://www.hotstar.com/*

### Website language(s)

English

### Other details

Its Indian version of disney+ That is now owned by disney.

**Comment by henrik9999** [comment] 2024-07-01 18:56
duplicate of #1742

**Closed by henrik9999** 2024-07-01 18:56 UTC
Labels: New Website
