### ISSUE TITLE
[Website Request] hianime.to 

### ISSUE THREAD

**Issue by TheBat913** [MALSync/MALSync#2315] opened 2024-03-01 15:00 UTC
### Website name

hianime.to

### Website link

https://hianime.to

### Website language(s)

English

### Other details

This is the new replacement for Aniwatch.to. They took down Aniwatch.to and replaced it with hianime.to.

**Comment by henrik9999** [comment] 2024-03-01 15:01
Duplicate of #2314

**Closed by henrik9999** 2024-03-01 15:01 UTC
Labels: New Website
