### ISSUE TITLE
MALSync stopped working in Netflix

### ISSUE THREAD

**Issue by Phoenomenal** [MALSync/MALSync#600] opened 2021-02-11 13:14 UTC
Just found a problem :
MALSync doesnt work on Netflix website starting 11 february.
Tried on Chrome and Edge browsers.  Everything worked fine just a few days ago 

Thats the message i got in page console: 

MAL-Sync Version: 0.8.5
MAL-Sync Settings Object  content-script.js:16 
M Sync Page Netflix content-script.js:1 
MAL-Sync checkNotifications content-script.js:14 
 Sending APH request...  antiphishing.js:9377
MAL-Sync Current Notification 5 content-script.js:14 
MAL-Sync No new notifications content-script.js:14 
Failed to load resource: the server responded with a status of 403 () GeqTh7:1 
Failed to load resource: net::ERR_FAILED chrome-extension://invalid/:1
No cast extension found   none:6 
MAL-Sync Object page_Netflix.js:1 page_Netflix.js:1
MAL-Sync No Anime  page_Netflix.js:1

**Comment by henrik9999** [comment] 2021-02-11 13:17
Duplicate of #599 but I will keep it open since it's more detailed

**Closed** 2021-03-16 10:58 UTC
Labels: Done for future release, bug
