### ISSUE TITLE
[Website Request] <pokeflix.tv>

### ISSUE THREAD

**Issue by Kolex06** [MALSync/MALSync#2685] opened 2024-11-11 13:10 UTC
### Suggestion

Website name
pokeflix

Website link
https://www.pokeflix.tv/

Website language(s)
English

Other details
Pokemon series, movies and specials

**Comment by henrik9999** [comment] 2024-11-11 13:11
Duplicate of #2655

**Closed by henrik9999** 2024-11-11 13:11 UTC
