### ISSUE TITLE
Ability to auto read manga

### ISSUE THREAD

**Issue by PythonCoderAS** [MALSync/MALSync#2195] opened 2023-12-18 15:12 UTC
### Suggestion

I would like an option that will automatically start "reading" the manga, because when reading a bunch of different one-shot entries the prompt gets slightly annoying. There could be caveats, like only doing auto read on local-only manga.

**Comment by henrik9999** [comment] 2023-12-18 15:15
Basically duplicate of https://github.com/MALSync/MALSync/issues/1100

**Closed by henrik9999** 2023-12-18 15:15 UTC
